// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBk6oc5AphAoxdYlvBZvGilrb65hW59vYA',
    appId: '1:37024419134:android:35de0e87ac51d069a5706f',
    messagingSenderId: '37024419134',
    projectId: 'flutter-95e6a',
    storageBucket: 'flutter-95e6a.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA52WNuoSqtEzv3aPtM6U9NzCwNw-DZW9I',
    appId: '1:37024419134:ios:54a23c692aec1818a5706f',
    messagingSenderId: '37024419134',
    projectId: 'flutter-95e6a',
    storageBucket: 'flutter-95e6a.firebasestorage.app',
    iosBundleId: 'com.example.mlNotaCerta',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCxubZtij5MgSoCNvVgyPZFRzqJZsrtfI0',
    appId: '1:37024419134:web:83e13e395be0f8b7a5706f',
    messagingSenderId: '37024419134',
    projectId: 'flutter-95e6a',
    authDomain: 'flutter-95e6a.firebaseapp.com',
    storageBucket: 'flutter-95e6a.firebasestorage.app',
  );
}
